### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by batarian71** [pasqu4le/clifm#2]
Hello. I am a graphic designer. I want to volunteer support for open source projects. If you want, I can design a logo for you. What do you say? Also tell me if you want something. I can design.

**Comment by pasqu4le** [comment]
Hey there, sure thing you can, it's very nice of you!

Also, I don't have anything in mind, so nothing to suggest you.

**Comment by pasqu4le** [comment]
Wow, I like the top-most the very much, I also think the color it's perfect.

The only thing I am not a fan of it's the tiny dot on the "i" and I am wondering if a monospaced font would fit better. What do you think?

**Comment by batarian71** [comment]
Which design do you like? I will change the font. I will send pr.

**Comment by pasqu4le** [comment]
I like the one on the top left, if you make a pr put the logo in the README and please reference yourself for your contribution.

**Comment by batarian71** [comment]
I sent pr.

**Comment by pasqu4le** [comment]
I love it! Thank you very much. I just merged the pr.
